=== amor3/ID2208/src/schema/ApplicantProfile.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="applicantProfile">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="personalInfo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="ssn"/>
                            <xs:element type="xs:string" name="personalLetter"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="studyRecord">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="universityName"/>
                            <xs:element type="xs:string" name="degree"/>
                            <xs:element type="xs:short" name="year"/>
                            <xs:element type="xs:byte" name="GPA"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="employmentRecord">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="employment" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:byte" name="companyId"/>
                                        <xs:element type="xs:string" name="companyName"/>
                                        <xs:element type="xs:string" name="telephoneNumber"/>
                                        <xs:element type="xs:date" name="fromDate"/>
                                        <xs:element type="xs:date" name="toDate"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== amor3/ID2208/src/xml_documents/ApplicantProfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<applicantProfile xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
                  xsi:noNamespaceSchemaLocation='file:/Users/johanand/NetBeansProjects/ID2208/src/schema/ApplicantProfile.xsd'>
  <personalInfo>
    <name>Johan Andersson</name>
    <ssn>801223-0432</ssn>
    <personalLetter>sdsd sdsd sdsdsss.</personalLetter>
  </personalInfo>
  <studyRecord>
    <universityName>KTH</universityName>
    <degree>Bachelor</degree>
    <year>2017</year>
    <GPA>100</GPA>
  </studyRecord>
  <employmentRecord>
    <employment>
      <companyId>1</companyId>
      <companyName>Microsoft</companyName>
      <telephoneNumber>08-11122</telephoneNumber>
      <fromDate>2012-01-22</fromDate>
      <toDate>2013-02-01</toDate>
    </employment>
    <employment>
      <companyId>1</companyId>
      <companyName>Microsoft</companyName>
      <telephoneNumber>08-11122</telephoneNumber>
      <fromDate>2012-01-22</fromDate>
      <toDate>2013-02-01</toDate>
    </employment>
    <employment>
      <companyId>1</companyId>
      <companyName>Microsoft</companyName>
      <telephoneNumber>08-11122</telephoneNumber>
      <fromDate>2012-01-22</fromDate>
      <toDate>2013-02-01</toDate>
    </employment>
  </employmentRecord>
</applicantProfile>
