=== amor3/ID2208/src/schema/CompanyInfo.xsd
<?xml version="1.0"?>

<xs:schema attributeFormDefault="unqualified" 
           elementFormDefault="qualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="companyInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="company" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="orgNo"/>
              <xs:element type="companyPhoneNo" name="phoneNumber"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="companyPhoneNo">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{2}-\d{5}"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== amor3/ID2208/src/xml_documents/CompanyInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<companyInfo xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
             xmlns='http://www.mc-boden.se/id2208/schema'
             xsi:schemaLocation='http://www.mc-boden.se/id2208/schema http://www.mc-boden.se/id2208/schema/CompanyInfo.xsd'>    
    <company>
        <name>Microsoft</name>
        <orgNo>123456-7800</orgNo>
        <phoneNumber>08-11122</phoneNumber>
    </company>
    <company>
        <name>Google</name>
        <orgNo>123456-7801</orgNo>>
        <phoneNumber>08-22233</phoneNumber>
    </company>
    <company>
        <name>Twitter</name>
        <orgNo>123456-7802</orgNo>
        <phoneNumber>08-33344</phoneNumber>
    </company>
</companyInfo>
