=== amor3/ID2208/src/schema/EmploymentRecord.xsd
<?xml version="1.0"?>
<xs:schema targetNamespace="http://www.mc-boden.se/id2208/schema" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.mc-boden.se/id2208/schema"
           elementFormDefault="qualified"> 

    <xs:element name="employmentRecords">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="ssn"/>
                <xs:element name="employment" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="orgNoType" name="orgNo" />                           
                            <xs:element type="xs:date" name="from"/>
                            <xs:element type="xs:date" name="to"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="orgNoType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{6}-\d{4}" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== amor3/ID2208/src/xml_documents/EmploymentRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<employmentRecords
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/Users/AMore/NetBeansProjects/WebService_hw_1/src/schema/EmploymentRecord.xsd'>
    <ssn>890110-0101</ssn>
    <employment>
        <orgNo>123456-7800</orgNo>
        <from>2006-01-01</from>
        <to>2007-12-30</to>
    </employment>
    <employment>
        <orgNo>123456-7801</orgNo>
        <from>2008-01-01</from>
        <to>2009-12-30</to>
    </employment>
    <employment>
        <orgNo>345226-7802</orgNo>
        <from>2010-01-01</from>
        <to>2014-12-30</to>
    </employment>
</employmentRecords>
