=== amor3/ID2208/src/schema/Transcript.xsd
<?xml version="1.0"?>
<xs:schema targetNamespace="http://www.mc-boden.se/id2208/schema" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.mc-boden.se/id2208/schema"
           elementFormDefault="qualified">  
    
    <xs:element name="transcript">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="university" type="xs:string"/>
                <xs:element name="degree" type="xs:string"/>
                <xs:element name="graduationYear" type="xs:int"/>

                <xs:element name="courses">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="course" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="ID" type="xs:string"/>
                                        <xs:element name="credits" type="xs:float"/>
                                        <xs:element name="grade" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>   
                        </xs:sequence>    
                    </xs:complexType>       
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== amor3/ID2208/src/xml_documents/Transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<transcript
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/Users/johanand/NetBeansProjects/ID2208/src/schema/Transcript.xsd'>
    <name>Johan Andersson</name>
    <university>KTH</university>
    <degree>Master</degree>
    <graduationYear>2017</graduationYear>
    <courses>
        <course>
            <name>Programming Web Services</name>
            <ID>ID2208</ID>
            <credits>7.5</credits>
            <grade>5</grade>
        </course>
        <course>
            <name>Programming Web Services</name>
            <ID>ID2208</ID>
            <credits>7.5</credits>
            <grade>5</grade>
        </course>
        <course>
            <name>Programming Web Services</name>
            <ID>ID2208</ID>
            <credits>7.5</credits>
            <grade>5</grade>
        </course>
    </courses>

</transcript>
